### ISSUE TITLE
关于RTB接口dsp_id、token等参数提交的问题

### ISSUE THREAD

**Issue by iamhanson** [xudongzhao-tencent/Tencent-AdExchange#2]
文档里没有看到如何提交dsp_id和token信息的说明，比如在提交广告主资质审核的时候，只列出了client_info，没有说明dsp_id和token如何提交。我在本地使用
header：  
Content-Type: application/json  
Authorization: token
## body：

{"client_info":[{"name":"client_name1","url":"http://www.qq.com","qualification_files":[{"file_name":"\u4f01\u4e1a\u8425\u4e1a\u6267\u7167","file_url":"http://adsfile.qq.com/1.jpg"},{"file_name":"ICP\u8bc1","file_url":"http://adsfile.qq.com/2.gif"}],"memo":"\u5907\u6ce8\u4fe1\u606f"}]}

得到的回复是
{"ret_code":1,"ret_msg":{"300":["dsp_id","token","client_info"]},"error_code":102}

![8af62bf4-7211-43f8-ae04-e79206b81dc9](https://cloud.githubusercontent.com/assets/3264635/14483980/29f7da6e-017f-11e6-9ccf-f5b5545ed6f9.png)

**Comment by pinkybs** [comment]
参考下这里
https://github.com/xudongzhao-tencent/Tencent-AdExchange/wiki/%E6%8E%A5%E5%8F%A3%E7%A4%BA%E4%BE%8B

**Comment by iamhanson** [comment]
请问这些参数是放在post的body里还是直接在url中，

**Comment by 231788364** [comment]
我也遇到和你一样的问题,请问你解决没?

**Comment by iamhanson** [comment]
@231788364 已经解决
在header里定义contenttype为form，然后数据放在body里发送
